[package]
name = "Stochastic-Volumetric-LED-Display"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
gumdrop = "0.8.1"
log = "0.4.22"
rand = "0.8.5"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
serialport = "4.6.1"
toml = "0.8.19"
