num_led = 100                                # Number of LEDS TOTAL, not per strip.
num_strips = 1

[communication]
communication_mode = 2                        # 1 indicates UDP, 2 indicates serial
host = "192.168.86.53"                        # UDP host
port = 8888                                   # UDP port (Default is 8888)
baud_rate = 3000000                                  # UDP port (Default is 8888)

serial_port_paths = ["/dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_94:A9:90:7B:49:70-if00"]

[recording]
record_data = true                            # If true, all commands will be recorded during the session
record_esp_data = true                        # If true, all commands will be recorded in a format that can be read by the ESP
unity_controls_recording = false              # If true, above two will be ignored and controlled by Unity
record_data_file = "record_data.vled"         # File to record vled data to
record_esp_data_file = "record_esp_data.bvled" # File to record bvled data to

[camera]
multi_camera = true
camera_index_1 = "4"                           # Can either be an index, or an RTSP address.
camera_index_2 = "6"
video_width = 1280
video_height = 720
no_background_frame_consumer=true

[scan]
scan_mode = 1
filter_color = 2
filter_range = 90
color_bright = 255

[unity_options]
num_container = 1
unity_ip = "127.0.0.1"
unity_ports = [5001, 6002, 6003]
unity_serial_baudrate = 921600
unity_position_files = ["largetanksecond.json"]
scale = 0.0008

[advanced.communication]
serial_read_timeout = 15
udp_read_timeout = 100
con_fail_limit = 2
use_queue = true
queue_size = 3
skip_confirmation = false

[advanced.camera]
no_video = false
get_events_streams_video = false
get_events_video_widgets = false
get_events_widgets_pos_index = 0
capture_frames = 4
cam2_overhead = true
cam2_overhead_flip = true

[advanced.hsv_overrides]
# hsv_red_override = []
# hsv_green_override = []
hsv_blue_override = [61, 0, 245, 95, 255, 255]

[advanced.transform]
# crop_override = [0, 0, 1280, 720]
# x_perspect_distort_adjust = 5
# y_perspect_distort_adjust = 0
#z_perspect_distort_adjust = 200

#x_stretch_adjust = 200
# y_stretch_adjust = 5
# z_stretch_adjust = 5

[advanced.misc]
print_send_back = false
no_controller = false
