name: Build for MacOS x86_64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-x86_64:
    name: Build for x86_64 MacOS
    runs-on: [self-hosted, MacOS]

    steps:
      - name: Add cargo to path
        run: export PATH="$PATH:/Users/docker/.cargo/bin/"
      - uses: actions/checkout@v4

      - name: Build release (x86_64)
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-x86_64
          path: target/release/svled