name: Build for RPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-rpi:
    name: Cross-compile for Raspberry Pi (armv7)
    runs-on: [self-hosted, Linux]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx (for qemu)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v3

      - name: Build Raspberry Pi Docker image
        run: |
          docker build -f .github/ci/docker/rpi-xcompile.Dockerfile -t rust-rpi-builder .

      - name: Cross-compile using Docker
        run: |
          docker run --rm \
            -v "$PWD":/usr/src/app \
            -w /usr/src/app \
            rust-rpi-builder \
            cargo-xbuild

      - name: list artifacts (debug)
        run: |
          ls target && \
          ls target/release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-rpi
          path: target/arm-unknown-linux-gnueabihf/release/
