name: Build for MacOS x86_64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-x86_64:
    name: Build for x86_64 MacOS
    runs-on: [self-hosted, MacOS]

    steps:
      - name: Build release (x86_64)
        run: /Users/docker/.cargo/bin/cargo build --release # Don't use absolute path

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-x86_64
          path: target/release/svled