name: Build for Windows x86_64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-x86_64:
    name: Build for x86_64 Windows
    runs-on: [self-hosted, Windows]

    steps:
      - uses: actions/checkout@v4

      - name: Chocolatey Action
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          # Arguments to pass to Chocolatey
          # don't install opencv here as we build the staticlib below
          args: install llvm wget strawberryperl
          # Docker image to use
          #image: # optional, default is ghcr.io/crazy-max/ghaction-chocolatey

      - name: Install OpenCV static lib
        run: |
          wget -O opencv.zip https://github.com/opencv/opencv/archive/refs/tags/4.11.0.zip
          wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/refs/tags/4.11.0.zip
          unzip opencv.zip && rm opencv.zip
          unzip opencv_contrib.zip && rm opencv_contrib.zip
          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=NO -DCMAKE_INSTALL_PREFIX="C:/opt/opencv" BUILD_CUDA_STUBS=OFF \
            -D BUILD_DOCS=OFF \
            -D BUILD_EXAMPLES=OFF \
            -D BUILD_IPP_IW=ON \
            -D BUILD_ITT=ON \
            -D BUILD_JASPER=OFF \
            -D BUILD_JAVA=OFF \
            -D BUILD_JPEG=ON \
            -D BUILD_OPENEXR=OFF \
            -D BUILD_OPENJPEG=ON \
            -D BUILD_PERF_TESTS=OFF \
            -D BUILD_PNG=ON \
            -D BUILD_PROTOBUF=ON \
            -D BUILD_SHARED_LIBS=OFF \
            -D BUILD_TBB=OFF \
            -D BUILD_TESTS=OFF \
            -D BUILD_TIFF=ON \
            -D BUILD_WEBP=ON \
            -D BUILD_WITH_DEBUG_INFO=OFF \
            -D BUILD_WITH_DYNAMIC_IPP=OFF \
            -D BUILD_ZLIB=ON \
            -D BUILD_opencv_apps=OFF \
            -D BUILD_opencv_python2=OFF \
            -D BUILD_opencv_python3=OFF \
            -D CMAKE_BUILD_TYPE=Release \
            -D CV_DISABLE_OPTIMIZATION=OFF \
            -D CV_ENABLE_INTRINSICS=ON \
            -D ENABLE_CONFIG_VERIFICATION=OFF \
            -D ENABLE_FAST_MATH=OFF \
            -D ENABLE_LTO=OFF \
            -D ENABLE_PIC=ON \
            -D ENABLE_PRECOMPILED_HEADERS=OFF \
            -D INSTALL_CREATE_DISTRIB=OFF \
            -D INSTALL_C_EXAMPLES=OFF \
            -D INSTALL_PYTHON_EXAMPLES=OFF \
            -D INSTALL_TESTS=OFF \
            -D OPENCV_ENABLE_MEMALIGN=OFF \
            -D OPENCV_ENABLE_NONFREE=ON \
            -D OPENCV_FORCE_3RDPARTY_BUILD=ON \
            -D OPENCV_GENERATE_PKGCONFIG=OFF \
            -D PROTOBUF_UPDATE_FILES=OFF \
            -D WITH_1394=OFF \
            -D WITH_ADE=ON \
            -D WITH_ARAVIS=OFF \
            -D WITH_CLP=OFF \
            -D WITH_CUBLAS=OFF \
            -D WITH_CUDA=OFF \
            -D WITH_CUFFT=OFF \
            -D WITH_EIGEN=ON \
            -D WITH_FFMPEG=OFF \
            -D WITH_GDAL=OFF \
            -D WITH_GDCM=OFF \
            -D WITH_GIGEAPI=OFF \
            -D WITH_GPHOTO2=OFF \
            -D WITH_GSTREAMER=OFF \
            -D WITH_GTK=OFF \
            -D WITH_HALIDE=OFF \
            -D WITH_IMGCODEC_HDcR=ON \
            -D WITH_IMGCODEC_PXM=ON \
            -D WITH_IMGCODEC_SUNRASTER=ON \
            -D WITH_INF_ENGINE=OFF \
            -D WITH_IPP=ON \
            -D WITH_ITT=ON \
            -D WITH_JASPER=OFF \
            -D WITH_JPEG=ON \
            -D WITH_LAPACK=OFF \
            -D WITH_LIBV4L=OFF \
            -D WITH_MATLAB=OFF \
            -D WITH_MFX=OFF \
            -D WITH_OPENCL=OFF \
            -D WITH_OPENCLAMDBLAS=OFF \
            -D WITH_OPENCLAMDFFT=OFF \
            -D WITH_OPENCL_SVM=OFF \
            -D WITH_OPENEXR=OFF \
            -D WITH_OPENGL=OFF \
            -D WITH_OPENMP=OFF \
            -D WITH_OPENNI2=OFF \
            -D WITH_OPENNI=OFF \
            -D WITH_OPENVX=OFF \
            -D WITH_PNG=ON \
            -D WITH_PROTOBUF=ON \
            -D WITH_PTHREADS_PF=ON \
            -D WITH_PVAPI=OFF \
            -D WITH_QT=OFF \
            -D WITH_QUIRC=ON \
            -D WITH_TBB=OFF \
            -D WITH_TIFF=ON \
            -D WITH_UNICAP=OFF \
            -D WITH_V4L=ON \
            -D WITH_VA=ON \
            -D WITH_VA_INTEL=ON \
            -D WITH_VTK=ON \
            -D WITH_WEBP=ON \
            -D WITH_XIMEA=OFF \
            -D WITH_XINE=OFF \
            -D WITH_AVIF=OFF \
            -D WITH_IMGCODEC_AVIF=OFF \
            -D OPENCV_EXTRA_MODULES_PATH="../opencv_contrib-4.11.0/modules" ../opencv-4.11.0 && \
          cmake --build . --target install --config Release --parallel 28
          cmake --install . --prefix C:/opt/opencv
          cd ..

      - name: Build
        run: |
          $env:OPENCV_LINK_LIBS="opencv_highgui4110,opencv_core4110,opencv_videoio4110,opencv_imgcodecs4110,opencv_imgproc4110,ippiw,ittnotify,ippicvmt,zlib"
          $env:OPENCV_LINK_PATHS="C:/opt/opencv/x64/vc17/staticlib"
          $env:OPENCV_INCLUDE_PATHS="C:/opt/opencv/include"
          $env:OPENCV_MSVC_CRT="static"
          cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-x86_64
          path: target/release/svled.exe